### PR TITLE
Update Roadmap 12.2023.md

### PR DESCRIPTION
**Pull request by MaudSimon**
Hoping I didn't mess everything up with my update and attempt to clean up format.

### CODE REVIEW

**Comment by nop33** [comment]
I tried to deploy it on www2 but it seems that the changes break something, I'll fix it later: https://github.com/alephium/www/actions/runs/7161247210/job/19496586683

**Review by nop33 — APPROVED** [review]
@MaudSimon I've fixed the issues and deployed the website on staging. Please, review how it looks and if everything is good feel free to merge this PR

https://www2.alephium.org/#milestones

**Comment by MaudSimon** [comment]
I have to change the order, the chronology isn't right. Will do in a bit.

**Comment by MaudSimon** [comment]
@nop33 I made some change to the order, I don't remember how to deploy to www2, could you do it for me (or remind me how I should do it) so I can double check what I changed ?

**Comment by MaudSimon** [comment]
Somehow the order I "coded" isn't respected in the ecosystem column, in 2022 & 2023. For example, in 2023 entries with order 14 & 15 are displayed between the entries with order 9 & 10.   I would need your help investigate @nop33 @mvaivre. Created issue: https://github.com/alephium/www/issues/149

**Comment by mvaivre** [comment]
_... checking_

**Comment by nop33** [comment]
@mvaivre I updated the algorithm that displays the sorted timeline entries, please have a look to review!

**Review by mvaivre — APPROVED** [review]

**Pull request merged**
