### PR TITLE
Update homepage.md

### PR DESCRIPTION
**Pull request by Sakrecoer**
Fix broken link. (temporary solution as this URL is likely to change soon)

### CODE REVIEW

**Comment by nop33** [comment]
There's another link like that:

```
https://wiki.alephium.org/smart-contract/Smart-Contract-Guide
```

our link checker caught it: https://github.com/alephium/www/runs/6225884246?check_suite_focus=true

**Comment by Sakrecoer** [comment]
For reference, the suggestions made by @nop33 

> It is true that we are lacking a proper smart contracts guide. What we have is:
> 
> - A blank wiki page called [Developing](https://wiki.alephium.org/dapps/Developing) that leads to @lf94 s gist with very little info
> - A wiki page called [Technical guide with a fullnode](https://wiki.alephium.org/dapps/Technical-Guide-With-A-Fullnode) that serves as a tutorial on creating and deploying a smart contract (for exchanging ALPH for tokens) on Alephium using the terminal
> - A GitHub repo called [voting-tutorial](https://github.com/alephium/voting-tutorial) that serves as a tutorial on creating and deploying a dApp on Alephium using a frontend app (not terminal)
> 
> So, all we have is tutorials, no reference guides.Maybe we should:
> 
> - Rename the [Technical guide with a fullnode](https://wiki.alephium.org/dapps/Technical-Guide-With-A-Fullnode) wiki page to Smart contract tutorial
> - Link the broken link to the Smart contract tutorial wiki page
> - Create a new wiki page called Voting dApp tutorial (or mention it in the Smart contract tutorial page) and link to the GitHub repo: https://github.com/alephium/voting-tutorial

**Comment by Sakrecoer** [comment]
Thank @nop33 But your supposed to be off-duty today! <3 Now go relax somewhere and crack open a cold one for me!! :sweat_smile:

**Comment by nop33** [comment]
haha, I am studying German and I should turn of my email app I guess 😆

**Pull request merged**
