### PR TITLE
Add membership logos in footer

### LINKED ISSUE #25: Integrate section for partners
Since we entered the UTXO Alliance and Bitcoin Association Switzerland, we need a new section for partnership. 
Typically it would include the logotype of the partner linking to their website and eventually a short description of said partner.

I'd be willing to make a mock-up if needed. 

UTXO logo: https://drive.google.com/file/d/1lf_uf0a4JuzyK49PcxNsQCMAiyDokG8R/view?usp=sharing
BAS logo: https://images.squarespace-cdn.com/content/v1/5895d62d2994ca86b0cd9807/1486226923132-GES7LLNU167XSPW77W83/image-asset.png?format=300w

### PR DESCRIPTION
**Pull request by nop33**
Closes #25

### CODE REVIEW

**Comment by nop33** [comment]
@MaudSimon @mvaivre @Sakrecoer here's an approach:

preview: https://www2.alephium.org/

image

**Comment by mvaivre** [comment]
I'd rather go for a centered version + reduce logo contrast (when not hovered).

image

Quick implementation here if needed: https://github.com/alephium/www/commit/98a07c9f9459b482094a1c2821983be3b215e9bd

**Comment by nop33** [comment]
Thanks for your feedback and contribution @mvaivre. I've updated the colors of the logos to match the ones of the links of the footer, and made sure that it looks good on mobile screens.

Ready to merge.

| Desktop | Mobile |
| -------- | ------ |
| image |  image |

**Comment by Sakrecoer** [comment]
I like it! :) Thank you @mvaivre for the suggestion and @nop33 for the work. For me it's fine to merge :purple_heart:

**Comment by mvaivre** [comment]
LGTM

**Pull request merged**
