### PR TITLE
Bring links back to technology section

### PR DESCRIPTION
**Pull request by nop33**
@mvaivre I had to change the height of the top gradient of the technology section to match the height of the section title because otherwise there is an area where the links are not clickable. See the video for an explanation. I tried to replicate the animation of the gradient as close as possible to your animation.

https://user-images.githubusercontent.com/1579899/176139724-2e932c93-f7dd-4a25-85c1-ce870e2a7a78.mp4

### CODE REVIEW

**Comment by mvaivre** [comment]
Thanks Ilias! Only issue now, the `overflow-x` caused by the gradient width..

**Comment by nop33** [comment]
ah, 💩 , didn't notice it, thanks... I'll work on it.

**Comment by nop33** [comment]
@mvaivre I still haven't figured out how to fix the overflow-x without adjusting the animation... I removed the scaleX for now, but the gradient animation doesn't look as cool as in your implementation. I'll stop working on it and I'll work on making the modals for mobile a bit prettier now. Let me know if I should continue the effort on the gradient animation.

**Comment by mvaivre** [comment]
@nop33 A `pointer-events: none` seems to do the trick?

**Comment by nop33** [comment]
OMG, you're a genius! TIL about `pointer-events`. Thanks! Updating my PR now... (also fixing the broken wiki link)

**Comment by mvaivre** [comment]
I've actually already commited the fix :)

**Pull request merged**
